// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwcphbavsbgngbczoncn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13Y3BoYmF2c2JnbmdiY3pvbmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MzgyMTEsImV4cCI6MjA1NTIxNDIxMX0.oC2SVRSGSB5N1xAfvst-ymMIzhAaB5PgR4kryDXkoug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);